package Vista;

/**
 *
 * @author juald
 */
public class VistaPrincipal extends javax.swing.JFrame
{

    /**
     * Creates new form VistaPrincipal
     */
    public VistaPrincipal()
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuBarPrincipal = new javax.swing.JMenuBar();
        jMenuConsultas = new javax.swing.JMenu();
        jMenuItemRealizarConsulta = new javax.swing.JMenuItem();
        jMenuItemCargarFicheroConsultas = new javax.swing.JMenuItem();
        jMenuItemGenerarFichero = new javax.swing.JMenuItem();
        jMenuDocumentos = new javax.swing.JMenu();
        jMenuItemIndexar = new javax.swing.JMenuItem();
        jMenuItemMostrarIndexados = new javax.swing.JMenuItem();
        jMenuItemGate = new javax.swing.JMenuItem();
        jMenuServidorSolr = new javax.swing.JMenu();
        jMenuItemCerrarServidor = new javax.swing.JMenuItem();
        jMenuItemDesconectar = new javax.swing.JMenuItem();
        jMenuSalir = new javax.swing.JMenu();
        jMenuItemSalir = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenuConsultas.setText("Consultas");

        jMenuItemRealizarConsulta.setText("Realizar consulta");
        jMenuItemRealizarConsulta.setActionCommand("RealizarConsulta");
        jMenuConsultas.add(jMenuItemRealizarConsulta);

        jMenuItemCargarFicheroConsultas.setText("Cargar fichero de consultas");
        jMenuItemCargarFicheroConsultas.setActionCommand("CargarFicheroConsultas");
        jMenuConsultas.add(jMenuItemCargarFicheroConsultas);

        jMenuItemGenerarFichero.setText("Generar fichero de evaluación");
        jMenuItemGenerarFichero.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jMenuItemGenerarFicheroActionPerformed(evt);
            }
        });
        jMenuConsultas.add(jMenuItemGenerarFichero);

        jMenuBarPrincipal.add(jMenuConsultas);

        jMenuDocumentos.setText("Documentos");

        jMenuItemIndexar.setText("Indexar documentos");
        jMenuItemIndexar.setActionCommand("IndexarDocumentos");
        jMenuItemIndexar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jMenuItemIndexarActionPerformed(evt);
            }
        });
        jMenuDocumentos.add(jMenuItemIndexar);

        jMenuItemMostrarIndexados.setText("Mostrar documentos indexados");
        jMenuItemMostrarIndexados.setActionCommand("MostrarDocumentosIndexados");
        jMenuDocumentos.add(jMenuItemMostrarIndexados);

        jMenuItemGate.setText("Indexar documentos GATE");
        jMenuItemGate.setActionCommand("SeleccionarFicheroGate");
        jMenuDocumentos.add(jMenuItemGate);

        jMenuBarPrincipal.add(jMenuDocumentos);

        jMenuServidorSolr.setText("Servidor Solr");

        jMenuItemCerrarServidor.setText("Cerrar Servidor");
        jMenuServidorSolr.add(jMenuItemCerrarServidor);

        jMenuItemDesconectar.setText("Desconectar");
        jMenuItemDesconectar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jMenuItemDesconectarActionPerformed(evt);
            }
        });
        jMenuServidorSolr.add(jMenuItemDesconectar);

        jMenuBarPrincipal.add(jMenuServidorSolr);

        jMenuSalir.setText("Salir");

        jMenuItemSalir.setText("Salir");
        jMenuSalir.add(jMenuItemSalir);

        jMenuBarPrincipal.add(jMenuSalir);

        setJMenuBar(jMenuBarPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 327, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemIndexarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jMenuItemIndexarActionPerformed
    {//GEN-HEADEREND:event_jMenuItemIndexarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemIndexarActionPerformed

    private void jMenuItemDesconectarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jMenuItemDesconectarActionPerformed
    {//GEN-HEADEREND:event_jMenuItemDesconectarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemDesconectarActionPerformed

    private void jMenuItemGenerarFicheroActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jMenuItemGenerarFicheroActionPerformed
    {//GEN-HEADEREND:event_jMenuItemGenerarFicheroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemGenerarFicheroActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JMenuBar jMenuBarPrincipal;
    public javax.swing.JMenu jMenuConsultas;
    public javax.swing.JMenu jMenuDocumentos;
    private javax.swing.JMenuItem jMenuItem1;
    public javax.swing.JMenuItem jMenuItemCargarFicheroConsultas;
    public javax.swing.JMenuItem jMenuItemCerrarServidor;
    public javax.swing.JMenuItem jMenuItemDesconectar;
    public javax.swing.JMenuItem jMenuItemGate;
    public javax.swing.JMenuItem jMenuItemGenerarFichero;
    public javax.swing.JMenuItem jMenuItemIndexar;
    public javax.swing.JMenuItem jMenuItemMostrarIndexados;
    public javax.swing.JMenuItem jMenuItemRealizarConsulta;
    public javax.swing.JMenuItem jMenuItemSalir;
    public javax.swing.JMenu jMenuSalir;
    public javax.swing.JMenu jMenuServidorSolr;
    // End of variables declaration//GEN-END:variables
}
