package Vista;

/**
 *
 * @author juald
 */
public class VistaIndexarDocumentos extends javax.swing.JPanel
{

    /**
     * Creates new form VistaIndexarDocumentos
     */
    public VistaIndexarDocumentos()
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jLabelndexar = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButtonSeleccionarFichero = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldFichero = new javax.swing.JTextField();

        jLabelndexar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabelndexar.setText("Indexar Documentos");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Seleccione el archivo para indexar sus documentos:");

        jButtonSeleccionarFichero.setText("Seleccionar fichero");
        jButtonSeleccionarFichero.setActionCommand("SeleccionarFichero");
        jButtonSeleccionarFichero.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButtonSeleccionarFicheroActionPerformed(evt);
            }
        });

        jLabel2.setText("Fichero seleccionado: ");

        jTextFieldFichero.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jTextFieldFicheroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldFichero, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(80, 80, 80)
                                .addComponent(jLabelndexar))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(101, 101, 101)
                                .addComponent(jButtonSeleccionarFichero)))))
                .addContainerGap(107, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelndexar)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jButtonSeleccionarFichero)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldFichero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addContainerGap(200, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSeleccionarFicheroActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButtonSeleccionarFicheroActionPerformed
    {//GEN-HEADEREND:event_jButtonSeleccionarFicheroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonSeleccionarFicheroActionPerformed

    private void jTextFieldFicheroActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jTextFieldFicheroActionPerformed
    {//GEN-HEADEREND:event_jTextFieldFicheroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldFicheroActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jButtonSeleccionarFichero;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelndexar;
    public javax.swing.JTextField jTextFieldFichero;
    // End of variables declaration//GEN-END:variables
}
